#interrogations, add punishment and warn, remove punishment and warn, open enderchest

command isd-panel <offlineplayer> <string>:
    trigger:
        if arg-1 is not online:
            send "player is not online" to player
            stop
        if arg-2 = "enderchest" or "ec":
            send "opened ender chest of %arg-1%" to player
            open ender chest of arg-1
        if arg-2 = warn:
            