function scp682(l: location):
    spawn ravager at {_l} with nbt nbt compound of "{Attributes:[{Name:generic.movement_speed,Base:0.25}],PersistenceRequired:1,Silent:1b,Tags:[""682""]}"
    set {_682} to last spawned entity
    set name of {_682} to "&2&lSCP-682 &r&c(KETER)"
    apply strength 1 without particles to {_682} for 1 year
    apply speed 3 without particles to {_682} for 1 year
    apply resistance 255 without particles to {_682} for 1 year