function returnItemStats(id: text,i: item) :: item:
	loop {item.attributes::*}:
		returnItemAttribute({_id},loop-value) is not 0
		set {_i} to addAttribute({_i},loop-value,returnItemAttribute({_id},loop-value),"add_number",returnItemSlots({_id})) if loop-value != "movement_speed"
		set {_i} to addAttribute({_i},loop-value,(returnItemAttribute({_id},loop-value)),"add_scalar",returnItemSlots({_id})) if loop-value = "movement_speed"
	loop {item.modifiers::*}:
		returnItemModifier({_id},loop-value) is not 0
		addModifier({_i},loop-value,returnItemModifier({_id},loop-value))
	return {_i}
