every 3 minutes:
    autoBroadcast()

function autoBroadcast():
    add 1 to {-broadcast}
    send "", " <##B82031>&lDANGERZONE", "", " <##B2BEB5>&l🔰 &fJoin our <link:https://discord.gg/dangerzone-688720684297617468/>&3&l[DISCORD]<reset>", "" to all players if {-broadcast} = 1
    send "", " <##B82031>&lDANGERZONE", "", " <##B2BEB5>&l🔰 &fSupport us by purchasing something off our <link:http://dangerzonemc.buycraft.net/>&e&l[STORE]<reset>", "" to all players if {-broadcast} = 2
    send "", " <##B82031>&lDANGERZONE", "", " <##B2BEB5>&l🔰 &fBecome a guard through joining our <link:https://discord.gg/dangerzone-688720684297617468/>&3&l[DISCORD]<reset> and applying!", "" to all players if {-broadcast} = 3
    send "", " <##B82031>&lDANGERZONE", "", " <##B2BEB5>&l🔰 &6&lNEW! &eGold shop! <link:https://dangerzonemc.buycraft.net/category/goldshop>&e&l[STORE]<reset>", "" to all players if {-broadcast} = 4
    send "", " <##B82031>&lDANGERZONE", "", " <##B2BEB5>&l🔰 &fSupport us by doing /ad in the minehut lobby!", "" to all players if {-broadcast} = 5
    set {-broadcast} to 0 if {-broadcast} = 5